"use strict";
let placetovisit = ["hongkong", "america", "pakistan", "brazil", "iran"];
// console.log(placetovisit);
// console.log(placetovisit.sort());
// console.log(placetovisit.sort().reverse());
// console.log(placetovisit);
// console.log(placetovisit.reverse());
// console.log(placetovisit.reverse());
let sortedarray = ["hongkong", "america", "pakistan", "brazil", "iran"];
sortedarray.sort();
console.log(sortedarray);
sortedarray.reverse();
console.log(sortedarray);
